version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: exchange_rates
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://api:8000

volumes:
  postgres_data:
