"""drop disabled column from exchange_rates table

Revision ID: 40da05a94f72
Revises: 18717332aae9
Create Date: 2025-08-19 22:59:31.955665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40da05a94f72'
down_revision: Union[str, Sequence[str], None] = '18717332aae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rates', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rates', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
